### ISSUE TITLE
plot_socialism renders empty plot

### ISSUE THREAD

**Issue by fabianaiolfi** [UniLuFS2020-ReplicationSeminar/OSF#2]
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/10398825/225252382-d9239dc6-bdb6-4cd2-82dc-531d04e2366d.png">

I cannot figure out why this code in [02-visualisation.R](https://github.com/UniLuFS2020-ReplicationSeminar/OSF/blob/6cfeca8bb861c55513ade8ff99bf279774d8f278/scripts/02-visualisation.R) renders an empty plot. Any ideas?

```
plot_socialism <- ERD %>%
  filter(v416e == 0) %>%
  filter(v416e == 1) %>%
  ggplot() +
  geom_point(aes(x=v005e, y=v705e)) +
  ggtitle("unemployment over time in cabinets with socialist majority") +
  xlab("date (out)") +
  ylab("unemployment after legislative term") +
  theme_minimal()
```

**Comment by simonweigold** [comment]
I just adjusted the filtering within the code, so that not all data is filtered out any more.
